name: Build and test SmartBotAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  PUBLISH_PATH: published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  PROJECT_PATH: src/server/SmartBotBlazorApp/SmartBotBlazorApp.csproj
  SOLUTION_PATH: src/server/SmartBotBlazorApp.sln
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.SOLUTION_PATH }}"
    - name: Build
      run: dotnet build "${{ env.SOLUTION_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.SOLUTION_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build
    - name: Publish
      run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.PUBLISH_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.PUBLISH_PATH }}
